services:
  javabd:
    build: javabd/
    command: java ./forSQLite.jar
    volumes:
      - tet:/usr/src/java_bd/db
      - ex:/usr/src/java_bd/xlsx

  client:
    build: client/
    command: python ./main.py
    ports:
      - 1234:1234
    volumes:
      - tet:/usr/src/tg/db
    network_mode: host
    depends_on:
      - javabd

volumes:
  tet:
    external: true
  ex:
    external: true